name: java setup

on:
  workflow_dispatch

jobs:
  java-setup:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java JDK
        uses: actions/setup-java@v4.6.0
        with:
          java-version: '17'
          distribution: 'temurin' 

      - name: Check Java Version
        run: java --version  
