name: Matrix Java Setup for Ubuntu & Microsoft

on: workflow_dispatch

jobs:
  matrix-jobs:
   runs-on: ${{matrix.os}}
   strategy:
     matrix:
       os:
       - ubuntu-latest
       - window-latest
       java-version: [17,21]
   steps:
     - name: Setup Java JDK
       uses: actions/setup-java@v4.6.0
       with:
        java-version: ${{matrix.java-version}}
        distribution: microsoft
     
        
    

