name: variable

on:
  workflow_dispatch

env: 
  MY_VAR: workflow  # Workflow-level env

jobs:
  variables:
    env:
      MY_VAR: jobs  # Job-level env
    runs-on: ubuntu_latest
    steps:
      - name: Print
        run: echo '${{env.MY_VAR}}'
        env:
          MY_VAR: steps  # Step-level env
